### PR TITLE
Feature/extension validation

### PR DESCRIPTION
**Pull request by ottonomy**
Implements simple extension validations.

Next: Validate more complex nested Extensions like GeoLocation and OBEE.

### CODE REVIEW

**Comment by mgylling** [comment]
Looks good to me.

**Comment by ottonomy** [comment]
Just added commit ea82b28. As it notes:
Refactor extension detection to happen while unflattened compacted JSON is in hand. Store this as a string in the task_meta instead of breaking it apart and stringing it back together later with some configuration-heavy system.

Next Steps:
* Update Extension Analysis unit tests to use this new format of VALIDATE_EXTENSION_NODE task meta
* Write and test small state util to find node by path list
* Adjust Extension Analysis function to use this new task meta.
* Adjust integration tests to expect this queuing system.
* Add an end-to-end test and ensure this method of discovering and testing extensions may be used in the API reliably.

**Comment by ottonomy** [comment]
Ok, this is ready for a review and merge. We'll come back to Extensions in a sprint or two.

@mgylling @ViktorHaag

**Comment by mgylling** [comment]
+1

**Pull request merged**
